Name:           ros-hydro-strands-webtools
Version:        0.0.1
Release:        1%{?dist}
Summary:        ROS strands_webtools package

Group:          Development/Libraries
License:        BSD
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-hydro-mjpeg-server
Requires:       ros-hydro-robot-pose-publisher
Requires:       ros-hydro-rosapi
Requires:       ros-hydro-rosauth
Requires:       ros-hydro-rosbridge-library
Requires:       ros-hydro-rosbridge-server
Requires:       ros-hydro-scitos-description
Requires:       ros-hydro-tf2-web-republisher
BuildRequires:  ros-hydro-catkin
BuildRequires:  ros-hydro-mjpeg-server
BuildRequires:  ros-hydro-robot-pose-publisher
BuildRequires:  ros-hydro-rosapi
BuildRequires:  ros-hydro-rosauth
BuildRequires:  ros-hydro-rosbridge-library
BuildRequires:  ros-hydro-rosbridge-server
BuildRequires:  ros-hydro-scitos-description
BuildRequires:  ros-hydro-tf2-web-republisher

%description
Remote control our robots via a browser

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/hydro" \
        -DCMAKE_PREFIX_PATH="/opt/ros/hydro" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/hydro

%changelog
* Wed Sep 10 2014 Lars Kunze <l.kunze@cs.bham.ac.uk> - 0.0.1-1
- Autogenerated by Bloom

* Thu Sep 04 2014 Lars Kunze <l.kunze@cs.bham.ac.uk> - 0.0.1-0
- Autogenerated by Bloom

